<?php
/*
 * vim: sw=4 ts=4 et wrap co=100
 */
?>
<h1>Administrator's View</h1>
<div id='mainLeftDiv'>
    <h2>Browse Activities</h2>
    <ul>
        <li class='navPanelItem'>By Assignment</li>
        <li class='navPanelItem'>By Approval Status</li>
        <li class='navPanelItem'>By Client</li>
        <li class='navPanelItem'>By Due Date</li>
        <li class='navPanelItem'>By End Date</li>
        <li class='navPanelItem'>By KITB Output</li>
        <li class='navPanelItem'>By Manager</li>
    </ul>
</div>
<div id='mainRightDiv'>
    <div id='topButtonsBar'>
        <input type='button' value='New Activity'>
    </div>
    <table id='explorableTable'><thead></thead><tbody></tbody></table>
</div>
