<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        $this->headLink()
            ->prependStylesheet('/css/ui-lightness/jquery-ui-1.8.4.custom.css')
            ->prependStylesheet('/css/global.css');

        $this->headScript()
            ->prependFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js')
            ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js');
        ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
        <?php echo $this->headTitle(); ?>
    </head>
    <body>
        <div id="layoutHeader">
            <h1>DPI - Time and Effort System</h1>
        </div>
        <div id="layoutContent">
            <?php echo $this->layout()->content; ?>
        </div>
        <div id="layoutfooter">
        </div>
    </body>
</html>